# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mario Kuzmanov - webpage
subtitle: > # ignore newlines until "description:"
    TBA
description: > # ignore newlines until "baseurl:"
    TBA
baseurl: ""
url: "https://mariokuzmanov.github.io"
github_username: MarioKuzmanov
encoding: utf-8
future: true

# Build settings
markdown: kramdown
